// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIWM51j1QAo_EB7G-SrMosGN0qLULuBE4',
    appId: '1:58689442801:web:4a77f7c607b46124eaea50',
    messagingSenderId: '58689442801',
    projectId: 'auth-session-e4d0c',
    authDomain: 'auth-session-e4d0c.firebaseapp.com',
    storageBucket: 'auth-session-e4d0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIzC-4lJpSzhlXmwHtp6_bhIrkYad9cAo',
    appId: '1:58689442801:android:7bd3370f50f3b072eaea50',
    messagingSenderId: '58689442801',
    projectId: 'auth-session-e4d0c',
    storageBucket: 'auth-session-e4d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4flovyvp3okvahsHn01TArmUrwjg2Q7g',
    appId: '1:58689442801:ios:771ce316c55c609feaea50',
    messagingSenderId: '58689442801',
    projectId: 'auth-session-e4d0c',
    storageBucket: 'auth-session-e4d0c.appspot.com',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4flovyvp3okvahsHn01TArmUrwjg2Q7g',
    appId: '1:58689442801:ios:d4a2362fb76001b5eaea50',
    messagingSenderId: '58689442801',
    projectId: 'auth-session-e4d0c',
    storageBucket: 'auth-session-e4d0c.appspot.com',
    iosBundleId: 'com.example.fireauth.RunnerTests',
  );
}
